### PR TITLE
Many significant improvements that worth an 1.3.5 release

### PR DESCRIPTION
**Pull request by jldelarbre**
Hello,
Almost one year since my last pull request. I progress slowly since I do it on my free time (no time last summer and autumn).
I think the result is enough interesting to release an 1.3.5 version, I have an 1.3.5-SNAPSHOT you can merge it if you want and release it as 1.3.5 release.

The release notes:

- Add Java enum to class diagram (in palette editor and java importer)
- Enhance display of class in class diagram:
	- Add icon decorator for abstract, static, final element
	- Separate package and class name in two lines
- Automatic synchronization of class diagram against imported java class
	- Work on java file modification and move
	- Work with generic class and nested class
	- Class connections (realization, association, composition aggregation...) are preserved when updating and synchronizing class diagram (conserve bendpoints, multiplicity...)
- Add option in configuration page: active or not creation of aggregation links on java import
- Bugs fix:
	- On java import to many aggregation links were created between imported class
	- Class diagram files (.cld) were becoming bigger and bigger in size, the more you use it and refresh diagram from java sources.

To be improved:
- Synchronize action uses existing code that requires a class diagram editor to be opened. The update of closed class diagrams involves an automatic opening of the class diagram. After it is closed and the active editor is restored. The whole operation is quite fast.
- The plugin is loaded lazily. So automatic synchronization of class diagram (with java code) can only start after the plugin has been started (=> open any UML diagram).

### CODE REVIEW

**Comment by takezoe** [comment]
@jldelarbre Thanks for a lot of improvements! I don't have much time to maintain AmetarasUML currently. Could you join development as a committer?

**Comment by aadrian** [comment]
+1 for a release.

**Comment by jldelarbre** [comment]
Ok to become a committer, but I do not expect to develop much more feature. As is it's fit my needs. Nevertheless I could eventually fix some bugs if they are not too much time consuming.

**Comment by takezoe** [comment]
@jldelarbre No problem. It would be nice if you will commit something when you need to do it.

**Comment by takezoe** [comment]
@jldelarbre I added you to this repository as collaborator.
I will merge this pull request into master and release a new version once. Please let me know if you have any other fixes.

**Comment by jldelarbre** [comment]
May be we can name the release 1.4.0. Since I may only fix some bugs in a near future, it will make more sense to realease the new version as 1.4.1, 1.4.2 ...
I do not know your release policy but for bugs correction 1.3.6 or even worse 1.3.5.1 would not be nice.

**Comment by takezoe** [comment]
I released as a feature `net.sf.amateras.modeler 1.1.0` this time. This feature is including umleditor, umleditor.java, db and xstream plugin. These plugins have different versions.

Since next version, I would like to release all plugins and feature as `2.0.0`, and update all plugin versions in every releases. I've already updated versions to `2.0.0.qualifier`. And I don't have clear release policy. Perhaps it will be `2.0.1` if that release contains only bug fix , and new feature release will be `2.1.0`.

**Comment by aadrian** [comment]
> I released as a feature net.sf.amateras.modeler 1.1.0 this time. 

Thank you.

> And I don't have clear release policy. Perhaps it will be 2.0.1 if that release contains only bug fix , and new feature release will be 2.1.0.

+1 http://semver.org/

Are there any release instructions, steps ?

**Comment by takezoe** [comment]
> Are there any release instructions, steps ?

No, but I will make it.

**Comment by takezoe** [comment]
@jldelarbre Release instruction is here:
https://github.com/takezoe/amateras-modeler/wiki/How-to-release

**Comment by takezoe** [comment]
@jldelarbre I added you to the update site repository as collaborator as well.
https://github.com/takezoe/amateras-update-site

The update site is provided on GitHub Pages. See `gh-pages` branch of the above repository.

**Comment by aadrian** [comment]
> https://github.com/takezoe/amateras-modeler/wiki/How-to-release

@takezoe Thank you for the detailed instructions

**Pull request merged**
