### PR TITLE
Enum support and icon decorator for abstract, static and final

### PR DESCRIPTION
**Pull request by jldelarbre**
Implementation of:
- Java Enum
- Add icon decorator for abstract, static, final element
- Separate package name and class name in class title

### CODE REVIEW

**Comment by takezoe** [comment]
@jldelarbre Looks good! However it would be nice if enum is editable on the diagram, not only drag and drop. Also I would like to generate enum code from the diagram.

**Comment by jldelarbre** [comment]
It would be nice and not very complicated to implement. For now I work on another topic. You can integrate it now, or may be I can look for that later.

**Comment by takezoe** [comment]
@jldelarbre OK, I will try to make them :-)

**Comment by jldelarbre** [comment]
Thank you. As you can see on "Graphs / Network" view, I am working on automatic synchronization between java source files and class diagram...

**Pull request closed without merging**
